# Generated by Django 2.2 on 2023-03-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paint'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='purchased_by',
            field=models.ManyToManyField(related_name='purchased_paints', to='myapp.User'),
        ),
    ]
